project:
  type: book

book:
  title: "Analisis del clima en Temixco"
  author: "Guillermo Barrios del Valle"
  date: "2/20/2024"
  director: "Instituto de Energias Renovables"
  chapters:
    - index.qmd
    - ./chapters/prefacio.qmd
    - ./chapters/windrose.qmd
    - ./chapters/referencias.qmd

bibliography: references/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: ./tex/tesisIER
    link-citations: true
    colorlinks: false

lang: es